# Generated by Django 5.2.3 on 2025-07-04 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('resource', 'Resource Added'), ('video', 'Video Uploaded'), ('note', 'Note Added'), ('new_course', 'New Course')], max_length=20),
        ),
        migrations.CreateModel(
            name='UpcomingCourseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upcoming_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notices.upcomingcourse')),
            ],
        ),
    ]
